"""add_voice_url_to_answer

Revision ID: 17db277af6ef
Revises: add_role_to_users_001
Create Date: 2026-03-15 21:46:05.244320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17db277af6ef'
down_revision = 'add_role_to_users_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('voice_url')

    # ### end Alembic commands ###
